### ISSUE TITLE
Use MMDrawerController

### ISSUE THREAD

**Issue by Richard1900** [dasmer/BlogDrawerPractice#1]
Hi Dasmer, do you know if I can use MMDrawerController without using is as the rootView?
Thanks in advance!

**Comment by dasmer** [comment]
Hey @Richard1900 , yes! you should be able to use MMDrawerController without using it as the rootView :)

**Comment by Richard1900** [comment]
I check both your project and MMDrawerController example project, MMDrawerController had been configured in AppDelegate, if I want to use it, but not as a root view, where should I configure it? In my comprehension we should use it before the centre(left,right) had been loaded, if I use it but not the root view, should I configure MMDrawerController in centre view's  - viewDidLoad method?
